### ISSUE TITLE
won't flash bin file

### ISSUE THREAD

**Issue by nerdralph** [probe-rs/cargo-flash#161]
**Describe the bug**
cargo flash --bin /c/tmp/buck50.bin --chip stm32f103c8
error: could not find `Cargo.toml` in `C:\msys64\home\parsons` or any parent directory
       Error Failed to run cargo build: exit code = Some(101)

cargo-flash properly detects my probe:
 cargo-flash --list-probes
The following devices were found:
[0]: CH55x CMSIS-DAP (VID: 1209, PID: c55d, Serial: NR, DAPLink)

cargo-flash 0.10.2

**Desktop (please complete the following information):**
Win7E MSYS2 (mingW64)

**Comment by Yatekii** [comment]
The `--bin` argument is not for this purpose. It is for selecting the `cargo` binary target, just like with `cargo build`.
You can use `cargo flash --elf xyz.elf` to flash an arbitrary ELF binary. Plain binary is not supported yet and most likely will never be. I am working on a new tool which will support all formats (ELF, HEX, BIN) and is geared towards C as well as Rust users.
