### ISSUE TITLE
AVR support

### ISSUE THREAD

**Issue by patrickelectric** [probe-rs/cargo-flash#164]
**Is your feature request related to a problem? Please describe.**
There is no option for AVR chips such as atmel328p

**Describe the solution you'd like**
Be able to flash atmel328p with cargo flash

**Describe alternatives you've considered**
Using sadly avrdude by hand

**Comment by Yatekii** [comment]
This is something that belongs to probe-rs and not cargo-flash. Once probe-rs has support, cargo-flash will automatically have it.
AVR support is a huge task, so don't expect it to be here tomorrow, but it is tracked here: https://github.com/probe-rs/probe-rs/discussions/391.
