### ISSUE TITLE
How to start a gdbserver?

### ISSUE THREAD

**Issue by Hoohaha** [probe-rs/cargo-flash#197]
**Is your feature request related to a problem? Please describe.**
Does this tool provide gdbserver? So I can use gdb to debug the device.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tiwalun** [comment]
`cargo-flash` has no built-in GDB server, but you can use [cargo-embed](https://github.com/probe-rs/cargo-embed) for this.

**Comment by Yatekii** [comment]
This feature is now in the `probe-rs-cli` on master :)

I am closing this for this reason. Please feel free to reopen if you are not satisfied with that solution :)
