### ISSUE TITLE
Do a 0.7 release with F3 support :)

### ISSUE THREAD

**Issue by jonathanpallant** [probe-rs/cargo-flash#28]
I'm looking for F3 support for a project, so I'd love to see a 0.7 release.

**Comment by Yatekii** [comment]
> I'm looking for F3 support for a project, so I'd love to see a 0.7 release.

Oh, we do not even need to do that :) we can do a patch release of probe-rs which cargo flash will automatically pick up :) good point tho! i'll try and release sometime today.
