### ISSUE TITLE
Detect when cargo flash is used for a library project

### ISSUE THREAD

**Issue by Tiwalun** [probe-rs/cargo-flash#3]
When cargo-flash is executed in a library project, it currently fails with the following output:

```console
$ cargo flash --chip nrf5182
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
    Flashing /home/dominik/Coding/fomu-rt/target/debug/fomu-rt
error: failed to flash /home/dominik/Coding/fomu-rt/target/debug/fomu-rt: No such file or directory (os error 2)
```

We should detect when the user tries to flash a library, and show a better error message indicating that flashing a library does not work.

**Comment by Yatekii** [comment]
This could also be eimplemented for https://github.com/probe-rs/cargo-embed.
