### ISSUE TITLE
`cargo flash` does not work inside members of a workspace

### ISSUE THREAD

**Issue by jonas-schievink** [probe-rs/cargo-flash#4]
It looks for `target` in the current directory, but in a workspace `target` is in the workspace root, resulting in a panic like this:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
```

**Comment by luojia65** [comment]
I met the same problem here (using `cargo flash` in workspace project root). The error message now:
![](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/XmrNjtrMCVHoffywHtmRzyha)
