### ISSUE TITLE
Cargo workspaces on Windows looks for files in workspace crate when using flash or embed

### ISSUE THREAD

**Issue by piedoom** [probe-rs/cargo-flash#40]
I am targeting the STM32F103 [following this tutorial.](https://jonathanklimt.de/electronics/programming/embedded-rust/rust-on-stm32-2/)

**To Reproduce**
1. Create a workspace root crate with at least one child crate
2. Flash or embed the crate on Windows 10
3. Error is shown `Error failed to flash \\?\C:\code\childcrate\target\thumbv7m-none-eabi\release\childcrate`. Relative to that path, the binaries are actually placed in `\\?\C:\code\target\thumbv7m-none-eabi\release\childcrate`. This target folder can be manually moved into the child crate, and flash will work successfully.

**Expected behavior**
When in a crate within a workspace, both `cargo build` and `cargo flash` place generated files in the workspace root. It would make sense to look there, unless the behavior is different on *nix.

**Desktop:**
 - Windows 10

**Extra details**
This may be related to #21

**Comment by Tiwalun** [comment]
Could you please check again? Should be fixed on the current master branch.
